"""create missions table

Revision ID: 519618739c4a
Revises: adc96de00c10
Create Date: 2026-06-30 01:25:47.744430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519618739c4a'
down_revision: Union[str, Sequence[str], None] = 'adc96de00c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('objective', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_index(
    "ix_missions_status",
    "missions",
    ["status"],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_index("ix_missions_status", table_name="missions")
    # ### end Alembic commands ###
